name: Build all NPM projects

on:
  push:
  pull_request:

jobs:
  vet:
    runs-on: ubuntu-latest
    name: Vet code
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm install
        shell: bash

      - name: Vet
        run: |
          npm run vet:ci
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: [vet]
    name: Test
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm install
        shell: bash

      - name: Test
        run: |
          npm run test:ci
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: [vet, test]
    name: Build
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm install
        shell: bash

      # Needed for esbuild
      - uses: actions/setup-go@v6
        with:
          go-version: "^1.23"
          cache-dependency-path: go.sum

      - name: Build
        run: |
          npm run build
        shell: bash

      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref_name == 'main'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4
